import React, { useMemo, useRef, useState } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import api from '../../services/api'
import ModalOverlay from '../ui/ModalOverlay'
import { printCredentialCards } from '../../utils/credentialCardsPrinter'

/**
 * Bulk-create no-email student accounts from a pasted list of names.
 *
 * One name per line ("First Last"). Usernames and kid-friendly passwords are
 * generated by the backend; after creation the admin can print login cards —
 * passwords are not retrievable later, so this is the moment to print.
 */
export default function BulkUsernameCreateModal({ orgId, orgSlug, orgName, onClose, onSuccess }) {
  const [namesText, setNamesText] = useState('')
  const [error, setError] = useState('')
  const [validationErrors, setValidationErrors] = useState([])
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const qrRef = useRef(null)

  const parsedStudents = useMemo(() => {
    return namesText
      .split('\n')
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => {
        const parts = line.split(/[\s,]+/).filter(Boolean)
        return {
          first_name: parts[0] || '',
          last_name: parts.slice(1).join(' ') || ''
        }
      })
  }, [namesText])

  const loginUrl = `${window.location.origin}/login/${orgSlug}`

  const handleSubmit = async () => {
    setError('')
    setValidationErrors([])

    if (parsedStudents.length === 0) {
      setError('Enter at least one student name (one per line, "First Last")')
      return
    }
    const missingLast = parsedStudents.findIndex(s => !s.last_name)
    if (missingLast !== -1) {
      setError(`Line ${missingLast + 1} needs both a first and last name`)
      return
    }
    if (parsedStudents.length > 100) {
      setError('Maximum 100 students per batch. Please split your list.')
      return
    }

    setLoading(true)
    try {
      const response = await api.post(
        `/api/admin/organizations/${orgId}/users/bulk-create-username`,
        { students: parsedStudents, org_role: 'student' }
      )
      setResult(response.data)
      onSuccess?.()
    } catch (err) {
      const data = err.response?.data
      if (data?.validation_errors) {
        setValidationErrors(data.validation_errors)
        setError('Some rows need fixing before any accounts are created:')
      } else {
        const errorData = data?.error || data?.message
        setError(typeof errorData === 'string' ? errorData : 'Failed to create accounts')
      }
    } finally {
      setLoading(false)
    }
  }

  const handlePrintCards = () => {
    const svg = qrRef.current?.querySelector('svg')
    const qrSvg = svg ? new XMLSerializer().serializeToString(svg) : null
    printCredentialCards({
      credentials: (result?.results || []).filter(r => r.status === 'created'),
      loginUrl,
      orgName: orgName || 'Your School',
      qrSvg
    })
  }

  const handleDownloadCsv = () => {
    const created = (result?.results || []).filter(r => r.status === 'created')
    const lines = ['name,username,password,login_url']
      .concat(created.map(r =>
        `"${r.name.replace(/"/g, '""')}",${r.username},${r.password},${loginUrl}`
      ))
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = 'student-login-credentials.csv'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const createdRows = (result?.results || []).filter(r => r.status === 'created')
  const failedRows = (result?.results || []).filter(r => r.status !== 'created')

  return (
    <ModalOverlay onClose={onClose} closeOnOverlayClick={!result}>
      <div className="bg-white rounded-xl w-full max-w-2xl my-auto max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between p-6 pb-4">
          <div>
            <h2 className="text-xl font-bold">
              {result ? 'Accounts Created' : 'Add Many Students (No Email)'}
            </h2>
            {!result && (
              <p className="text-sm text-gray-500 mt-1">
                Paste your class list — one student per line, first name then last name.
              </p>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="px-6 pb-6 overflow-y-auto flex-1">
          {/* Hidden QR used for the printable cards */}
          <div ref={qrRef} className="hidden" aria-hidden="true">
            <QRCodeSVG value={loginUrl} size={64} level="M" includeMargin={false} />
          </div>

          {!result ? (
            <>
              <textarea
                value={namesText}
                onChange={(e) => setNamesText(e.target.value)}
                rows={10}
                placeholder={'Maya Jones\nLiam Smith\nOlivia Nguyen'}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 font-mono text-sm focus:ring-2 focus:ring-optio-purple/20 focus:border-optio-purple outline-none"
              />
              <p className="text-xs text-gray-500 mt-2">
                {parsedStudents.length > 0
                  ? `${parsedStudents.length} student${parsedStudents.length === 1 ? '' : 's'} ready. Usernames and passwords are generated automatically.`
                  : 'Usernames and kid-friendly passwords (like "1234apple") are generated automatically.'}
              </p>

              {error && (
                <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
                  {error}
                  {validationErrors.length > 0 && (
                    <ul className="mt-1 list-disc list-inside">
                      {validationErrors.map((v, i) => (
                        <li key={i}>Row {v.row} ({v.name}): {v.errors.join(', ')}</li>
                      ))}
                    </ul>
                  )}
                </div>
              )}

              <div className="flex justify-end gap-3 mt-4">
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={loading || parsedStudents.length === 0}
                  className="px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-optio-purple to-optio-pink rounded-lg hover:opacity-90 disabled:opacity-50"
                >
                  {loading ? 'Creating...' : `Create ${parsedStudents.length || ''} Account${parsedStudents.length === 1 ? '' : 's'}`}
                </button>
              </div>
            </>
          ) : (
            <>
              <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-sm text-amber-800 mb-4">
                Passwords are shown only once. Print the login cards or download
                the CSV now — you will not be able to see these passwords again.
              </div>

              <div className="overflow-x-auto border border-gray-200 rounded-lg">
                <table className="min-w-full divide-y divide-gray-200 text-sm">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase">Student</th>
                      <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase">Username</th>
                      <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase">Password</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {createdRows.map((r) => (
                      <tr key={r.user_id}>
                        <td className="px-4 py-2">{r.name}</td>
                        <td className="px-4 py-2 font-mono">{r.username}</td>
                        <td className="px-4 py-2 font-mono">{r.password}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {failedRows.length > 0 && (
                <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
                  {failedRows.length} account{failedRows.length === 1 ? '' : 's'} failed:
                  <ul className="mt-1 list-disc list-inside">
                    {failedRows.map((r, i) => (
                      <li key={i}>{r.name}: {r.error}</li>
                    ))}
                  </ul>
                </div>
              )}

              <p className="text-xs text-gray-500 mt-3">
                Students sign in at <span className="font-mono">{loginUrl}</span>
              </p>

              <div className="flex flex-wrap justify-end gap-3 mt-4">
                <button
                  onClick={handleDownloadCsv}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200"
                >
                  Download CSV
                </button>
                <button
                  onClick={handlePrintCards}
                  className="px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-optio-purple to-optio-pink rounded-lg hover:opacity-90"
                >
                  Print Login Cards
                </button>
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200"
                >
                  Done
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </ModalOverlay>
  )
}
