import React, { useState } from 'react'
import api from '../../services/api'

/**
 * Modal for creating a student account with username (no email required).
 * Password is auto-generated by the backend in kid-friendly format (e.g., "1234apple").
 * Shows credentials after successful creation.
 */
export default function CreateUsernameStudentModal({ orgId, orgSlug, onClose, onSuccess }) {
  const [formData, setFormData] = useState({
    username: '',
    first_name: '',
    last_name: ''
  })
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [createdCredentials, setCreatedCredentials] = useState(null)

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    setError('')

    // Validate required fields
    if (!formData.first_name.trim()) {
      setError('First name is required')
      setLoading(false)
      return
    }
    if (!formData.last_name.trim()) {
      setError('Last name is required')
      setLoading(false)
      return
    }
    if (!formData.username.trim()) {
      setError('Username is required')
      setLoading(false)
      return
    }

    try {
      const response = await api.post(`/api/admin/organizations/${orgId}/users/create-username`, {
        username: formData.username.trim().toLowerCase(),
        first_name: formData.first_name.trim(),
        last_name: formData.last_name.trim()
      })

      // Show credentials (password is auto-generated by backend)
      setCreatedCredentials({
        username: response.data.login_credentials.username,
        password: response.data.login_credentials.password,
        loginUrl: `${window.location.origin}${response.data.login_credentials.login_url}`,
        studentName: `${formData.first_name} ${formData.last_name}`
      })

    } catch (err) {
      const errorData = err.response?.data?.error || err.response?.data?.message || err.response?.data
      setError(typeof errorData === 'string' ? errorData : errorData?.message || 'Failed to create student')
    } finally {
      setLoading(false)
    }
  }

  const copyCredentials = () => {
    const text = `Student Login Credentials for ${createdCredentials.studentName}

Login URL: ${createdCredentials.loginUrl}
Username: ${createdCredentials.username}
Password: ${createdCredentials.password}

Please keep this information secure.`

    navigator.clipboard.writeText(text)
    alert('Credentials copied to clipboard!')
  }

  const handleDone = () => {
    onSuccess()
    onClose()
  }

  // Show credentials after creation
  if (createdCredentials) {
    return (
      <div className="fixed top-0 left-0 right-0 bottom-0 w-full h-full bg-black/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
        <div className="bg-white rounded-xl p-6 w-full max-w-md my-auto">
          <div className="text-center mb-6">
            <div className="mx-auto w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mb-4">
              <svg className="w-6 h-6 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h2 className="text-2xl font-bold text-gray-900">Student Created!</h2>
            <p className="text-gray-600 mt-1">Share these login credentials with the student.</p>
          </div>

          <div className="bg-gray-50 rounded-lg p-4 space-y-3 mb-6">
            <div>
              <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide">Student Name</label>
              <p className="text-gray-900 font-medium">{createdCredentials.studentName}</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide">Login URL</label>
              <p className="text-optio-purple font-medium break-all">{createdCredentials.loginUrl}</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide">Username</label>
              <p className="text-gray-900 font-mono bg-white px-2 py-1 rounded border">{createdCredentials.username}</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide">Password</label>
              <p className="text-gray-900 font-mono bg-white px-2 py-1 rounded border">{createdCredentials.password}</p>
            </div>
          </div>

          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-6">
            <p className="text-sm text-yellow-800">
              <strong>Important:</strong> Save or copy these credentials now. You can reset the password later from the user settings, but you won't see this password again.
            </p>
          </div>

          <div className="flex gap-3">
            <button
              onClick={copyCredentials}
              className="flex-1 px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50 font-medium inline-flex items-center justify-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Copy All
            </button>
            <button
              onClick={handleDone}
              className="flex-1 px-4 py-2 bg-gradient-to-r from-optio-purple to-optio-pink text-white rounded-lg hover:opacity-90 font-medium"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="fixed top-0 left-0 right-0 bottom-0 w-full h-full bg-black/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-white rounded-xl p-6 w-full max-w-md my-auto">
        <h2 className="text-2xl font-bold mb-2">Create Student Account</h2>
        <p className="text-gray-600 text-sm mb-6">
          Create a student account using username. No email address required. A simple password will be generated automatically.
        </p>

        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-2 gap-3 mb-4">
            <div>
              <label className="block text-sm font-medium mb-1">First Name <span className="text-red-500">*</span></label>
              <input
                type="text"
                value={formData.first_name}
                onChange={(e) => setFormData({ ...formData, first_name: e.target.value })}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:ring-2 focus:ring-optio-purple/20 focus:border-optio-purple outline-none"
                placeholder="John"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Last Name <span className="text-red-500">*</span></label>
              <input
                type="text"
                value={formData.last_name}
                onChange={(e) => setFormData({ ...formData, last_name: e.target.value })}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:ring-2 focus:ring-optio-purple/20 focus:border-optio-purple outline-none"
                placeholder="Doe"
              />
            </div>
          </div>

          <div className="mb-4">
            <label className="block text-sm font-medium mb-1">Username <span className="text-red-500">*</span></label>
            <input
              type="text"
              value={formData.username}
              onChange={(e) => setFormData({ ...formData, username: e.target.value.toLowerCase() })}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:ring-2 focus:ring-optio-purple/20 focus:border-optio-purple outline-none"
              placeholder="john.doe"
            />
            <p className="text-xs text-gray-500 mt-1">Letters, numbers, dots, underscores, and hyphens only</p>
          </div>

          <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
            <p className="text-sm text-blue-800">
              A simple password will be generated automatically (like "1234apple"). You'll see it after creating the account.
            </p>
          </div>

          {error && (
            <div className="mb-4 p-3 bg-red-50 text-red-700 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div className="flex gap-3">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 px-4 py-2 bg-gradient-to-r from-optio-purple to-optio-pink text-white rounded-lg hover:opacity-90 disabled:opacity-50"
            >
              {loading ? 'Creating...' : 'Create Student'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
