[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x', 'python311', 'gcc']

[phases.install]
cmds = ['npm install', 'cd backend && pip install -r ../requirements.txt']

[phases.build]
cmds = ['cd frontend && npm install && npm run build']

[start]
cmd = 'cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --log-level debug --access-logfile - --error-logfile -'