[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["python"]

[[build.nixpacks.phases]]
name = "install"
cmds = ["pip install -r requirements.txt"]

[deploy]
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 300