/**
 * Test Token Validation
 *
 * Tests that tokens generated by /spark/token endpoint work with /api/auth/me
 */

// Using native fetch in Node 18+

const API_URL = 'https://optio-dev-backend.onrender.com';

async function testTokenFlow() {
  console.log('='.repeat(80));
  console.log('TESTING SPARK TOKEN VALIDATION');
  console.log('='.repeat(80));
  console.log();

  try {
    // Step 1: Generate SSO token and get auth code
    console.log('Step 1: Generating Spark SSO token...');
    const jwt = require('jsonwebtoken');
    const SECRET = process.env.SPARK_SSO_SECRET;

    if (!SECRET) {
      console.error('❌ ERROR: SPARK_SSO_SECRET environment variable not set');
      console.error('Set it with: export SPARK_SSO_SECRET=your_secret_here');
      return;
    }

    const ssoToken = jwt.sign({
      sub: 'test_student_001',
      email: 'spark-test@optioeducation.com',
      given_name: 'Spark',
      family_name: 'TestStudent',
      role: 'student',
      iat: Math.floor(Date.now() / 1000),
      exp: Math.floor(Date.now() / 1000) + 600
    }, SECRET);

    console.log('SSO JWT generated');
    console.log();

    // Step 2: Call SSO endpoint to get auth code
    console.log('Step 2: Calling /spark/sso endpoint...');
    const ssoResponse = await fetch(`${API_URL}/spark/sso?token=${ssoToken}`, {
      redirect: 'manual' // Don't follow redirect
    });

    if (ssoResponse.status !== 302) {
      console.error(`❌ SSO endpoint returned ${ssoResponse.status} instead of 302`);
      return;
    }

    const location = ssoResponse.headers.get('location');
    const authCode = new URL(location).searchParams.get('code');
    console.log(`✅ Got auth code: ${authCode.substring(0, 20)}...`);
    console.log();

    // Step 3: Exchange auth code for access/refresh tokens
    console.log('Step 3: Exchanging auth code for tokens...');
    const tokenResponse = await fetch(`${API_URL}/spark/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code: authCode })
    });

    if (tokenResponse.status !== 200) {
      console.error(`❌ Token exchange failed with status ${tokenResponse.status}`);
      const errorData = await tokenResponse.json();
      console.error('Error:', errorData);
      return;
    }

    const tokens = await tokenResponse.json();
    console.log(`✅ Got access token: ${tokens.access_token.substring(0, 30)}...`);
    console.log(`✅ Got refresh token: ${tokens.refresh_token.substring(0, 30)}...`);
    console.log();

    // Step 4: Test access token with /api/auth/me
    console.log('Step 4: Testing access token with /api/auth/me...');
    const meResponse = await fetch(`${API_URL}/api/auth/me`, {
      headers: {
        'Authorization': `Bearer ${tokens.access_token}`
      }
    });

    console.log(`Response status: ${meResponse.status}`);

    if (meResponse.status === 200) {
      const userData = await meResponse.json();
      console.log('✅ SUCCESS! Token is valid');
      console.log('User data:', JSON.stringify(userData, null, 2));
    } else {
      console.log('❌ FAILED! Token is invalid');
      const errorData = await meResponse.json();
      console.log('Error:', errorData);
    }

  } catch (error) {
    console.error('❌ Test failed with error:', error.message);
  }
}

testTokenFlow();
