/**
 * What role is this user, really — the one rule, shared by both clients.
 *
 * A user's role arrives in one of three shapes (CLAUDE.md, Role System):
 * platform users carry it in `role`; org-managed users carry
 * `role='org_managed'` with the real role in `org_role`, or in the newer
 * `org_roles` array when they hold several.
 *
 * Both apps had their own copy of this and both said in their own docstrings
 * that they mirrored the other. They agreed with each other on the shapes they
 * both handled, and the mobile one did not handle `org_roles` at all.
 *
 * THIS FILE DELIBERATELY REPRODUCES THE SERVER, QUIRKS INCLUDED. It is not a
 * tidied-up version of the rule: `backend/utils/roles.py` decides what an
 * endpoint actually allows, and a client that improves on it offers controls
 * whose save is refused. `shared/roleCases.json` holds the corpus, generated by
 * running the Python over these inputs, and all three sides have a test that
 * reads it.
 *
 * Not handled here, on purpose: the backend's `apply_role_view` narrowing (a
 * superadmin viewing the app as another role) and v2's `previewRoleStore`.
 * Both are layered on top by their own callers.
 */

export interface RoleShape {
  role?: string | null;
  org_role?: string | null;
  org_roles?: string[] | null;
}

/** users.role — the platform role column. Mirrors UserRole in roles.py. */
export const VALID_ROLES = [
  'student', 'parent', 'advisor', 'observer', 'org_admin', 'org_managed', 'superadmin',
] as const;

/**
 * users.org_role / users.org_roles. Mirrors OrgRole in roles.py.
 * `campus_coordinator` is here and NOT in VALID_ROLES: it is an org role only,
 * so it can never appear in users.role.
 */
export const VALID_ORG_ROLES = [
  'student', 'parent', 'advisor', 'observer', 'org_admin', 'campus_coordinator',
] as const;

const isValidOrgRole = (r: unknown): r is string =>
  typeof r === 'string' && (VALID_ORG_ROLES as readonly string[]).includes(r);

/**
 * The user's single effective role — get_effective_role in roles.py.
 *
 * Note the org_roles branch checks only the FIRST element and falls through to
 * org_role when it is not a valid org role. It does not go looking for the
 * first VALID element; that is the server's behaviour and this matches it.
 */
export function effectiveRoleOf(user: RoleShape | null | undefined): string | null {
  // No user is not a role. The server never sees this case -- it only ever
  // resolves a row it has already loaded -- and both clients relied on
  // null-in/null-out while a session is still loading. A logged-out user who
  // resolved to 'student' would flash student chrome on every cold start.
  if (!user) return null;
  const role = user.role ?? 'student';
  if (role === 'superadmin') return 'superadmin';

  if (role === 'org_managed') {
    const orgRoles = user.org_roles;
    if (Array.isArray(orgRoles) && orgRoles.length > 0) {
      const primary = orgRoles[0];
      if (isValidOrgRole(primary)) return primary;
    }
    const orgRole = user.org_role;
    if (orgRole && isValidOrgRole(orgRole)) return orgRole;
    // The server logs a warning here and calls them a student.
    return 'student';
  }

  return role;
}

/**
 * Every effective role — get_effective_roles in roles.py. Use this for "does
 * this user hold ANY of these roles".
 *
 * Falls through to org_role when org_roles holds nothing valid, exactly as the
 * singular does. Until 2026-09-07 the server's plural did not: it filtered the
 * array to nothing and returned [], so an account whose org_roles held an
 * unknown value resolved to a real role through effectiveRoleOf and passed no
 * role check anywhere, because every gate asks "is any of my roles in this
 * list" and an empty list answers no to all of them. Unreachable through the
 * database (users.org_roles carries the valid_org_roles CHECK constraint),
 * which is why it survived — a lockout that depended on that constraint
 * staying correct.
 */
export function effectiveRolesOf(user: RoleShape | null | undefined): string[] {
  if (!user) return [];
  const role = user.role ?? 'student';
  if (role === 'superadmin') return ['superadmin'];

  if (role === 'org_managed') {
    const orgRoles = user.org_roles;
    if (Array.isArray(orgRoles) && orgRoles.length > 0) {
      const valid = orgRoles.filter(isValidOrgRole);
      if (valid.length > 0) return valid;
    }
    const orgRole = user.org_role;
    if (orgRole && isValidOrgRole(orgRole)) return [orgRole];
    return ['student'];
  }

  return [role];
}

/**
 * True when the user holds ANY of the given roles.
 *
 * Looser than `effectiveRolesOf(...).includes(...)` on purpose, and this is the
 * behaviour both clients already had: it matches the raw `role`, the
 * `org_roles` array and the legacy `org_role` without validating any of them.
 * Chrome gates use it, and a gate that hides a control is allowed to be
 * generous where a gate that grants access is not. For anything that decides
 * access, ask the server.
 */
export function userHasRole(
  user: RoleShape | null | undefined,
  ...roles: string[]
): boolean {
  if (!user || roles.length === 0) return false;
  return roles.some((role) => (
    !!role && (
      user.role === role
      || (Array.isArray(user.org_roles) && user.org_roles.includes(role))
      || user.org_role === role
    )
  ));
}
