appId: com.optioeducation.optio
name: Optio Mobile E2E Tests

env:
  TEST_STUDENT_EMAIL: ${E2E_STUDENT_EMAIL}
  TEST_STUDENT_PASSWORD: ${E2E_STUDENT_PASSWORD}
  TEST_PARENT_EMAIL: ${E2E_PARENT_EMAIL}
  TEST_PARENT_PASSWORD: ${E2E_PARENT_PASSWORD}
  TEST_OBSERVER_EMAIL: ${E2E_OBSERVER_EMAIL}
  TEST_OBSERVER_PASSWORD: ${E2E_OBSERVER_PASSWORD}
