import { describe, it, expect } from 'vitest'
import { effectiveRoleOf, effectiveRolesOf, userHasRole, VALID_ROLES, VALID_ORG_ROLES } from '@shared/roles'
import cases from '@shared/roleCases.json'

/**
 * The web half of the role conformance (QF-01).
 *
 * `shared/roleCases.json` is generated by running `backend/utils/roles.py` over
 * these inputs, and the backend, this app and the mobile app each have a test
 * that reads it. Reading the three implementations against each other catches
 * nothing -- they are written in different languages against different data
 * shapes. What they owe each other is the same answer.
 */

describe('role resolution conforms to the server', () => {
  it('is testing something', () => {
    expect(cases.cases.length).toBeGreaterThanOrEqual(15)
  })

  it('knows the same role vocabulary as UserRole/OrgRole', () => {
    expect([...VALID_ROLES].sort()).toEqual(cases.validRoles)
    expect([...VALID_ORG_ROLES].sort()).toEqual(cases.validOrgRoles)
    // campus_coordinator is an org role and NOT a platform role: it must never
    // be writable into users.role.
    expect(VALID_ORG_ROLES).toContain('campus_coordinator')
    expect(VALID_ROLES).not.toContain('campus_coordinator')
  })

  for (const c of cases.cases) {
    it(`effectiveRoleOf: ${c.why}`, () => {
      expect(effectiveRoleOf(c.user)).toBe(c.effectiveRole)
    })
    it(`effectiveRolesOf: ${c.why}`, () => {
      expect(effectiveRolesOf(c.user)).toEqual(c.effectiveRoles)
    })
  }

  // The server only ever resolves a row it has already loaded, so it has no
  // opinion here; both clients do, and both relied on it before the share.
  it('answers null for no user rather than calling them a student', () => {
    expect(effectiveRoleOf(null)).toBeNull()
    expect(effectiveRoleOf(undefined)).toBeNull()
    expect(effectiveRolesOf(null)).toEqual([])
  })

  it('userHasRole reads all three shapes a role arrives in', () => {
    expect(userHasRole({ role: 'advisor' }, 'advisor')).toBe(true)
    expect(userHasRole({ role: 'org_managed', org_role: 'advisor' }, 'advisor')).toBe(true)
    expect(userHasRole({ role: 'org_managed', org_roles: ['parent', 'advisor'] }, 'advisor')).toBe(true)
    expect(userHasRole({ role: 'org_managed', org_roles: ['parent'] }, 'advisor')).toBe(false)
    expect(userHasRole(null, 'advisor')).toBe(false)
    expect(userHasRole({ role: 'advisor' })).toBe(false)
  })
})
