-- Success criteria: 2-4 short checkable bullets defining "done" for a task.
-- Generated by AI at personalization time (shaped by challenge level),
-- persisted when tasks are accepted/finalized, shown at evidence submission.
-- Stored as a jsonb array of strings; NULL = no criteria (legacy tasks,
-- student-created tasks without criteria).
ALTER TABLE user_quest_tasks ADD COLUMN IF NOT EXISTS success_criteria jsonb;
ALTER TABLE quest_sample_tasks ADD COLUMN IF NOT EXISTS success_criteria jsonb;
